export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";


export const FETCH_INGREDIENT_FAILED = "FETCH_INGREDIENT_FAILED";
export const SET_INGREDIENT = "SET_INGREDIENT";

export const PURCHAS_BURGER_START = " PURCHAS_BURGER_START";
export const PURCHAS_BURGER_SUCCESS = " PURCHAS_BURGER_SUCCESS";
export const PURCHAS_BURGER_FAILED = " PURCHAS_BURGER_FAILED";